### ISSUE TITLE
Facebook expiration is not set

### ISSUE THREAD

**Issue by martinbean** [laravel/socialite#354] opened 2019-03-29 12:22 UTC
- Socialite Version: 3.2.0
- Laravel Version: 5.7.28
- PHP Version: 7.1.23
- Database Driver & Version: Postgres 10.6

### Description:
It seems Facebook’s changed how it returns access tokens since Socialite was last updated and the expiration date is no longer surfaced (and therefore set by Socialite). It’s also unclear whether the token Socialite returns is a “short-lived” token or a “long-lived” token.

It _is_ possible to “debug” a Facebook access token: (https://developers.facebook.com/docs/graph-api/reference/v3.2/debug_token). But again, this is confusing as that endpoint returns two “expires” timestamps: an `expires_at` timestamp and a `data_access_expires_at` timestamp.

I’m not sure whether it would be acceptable for Socialite to make a second HTTP call just to fetch the `expires_at` timestamp value, but it sure would be helpful in my application(s) so that for stored access tokens, I can see when they expired and if they need refreshing.

### Steps To Reproduce:
1. Create a route to authenticate with Facebook.
2. Create a route to handle the callback from Facebook.
3. Observe that `expiresIn` is `null` when calling `Socialite::driver('facebook')->user()`.

**Comment by driesvints** [comment] 2019-03-29 14:38
I can't even find the documentation about the original access token endpoint anymore. Can someone link to it for me? I want to see what the response looks like and how it differs in the latest version.

**Comment by martinbean** [comment] 2019-03-29 16:21
@driesvints The endpoint itself doesn’t seem to be documented, but it seems to return a JSON object with just two keys:

```json
{
    "access_token": "[redacted]",
    "token_type": "bearer"
}
```

**Comment by driesvints** [comment] 2019-03-29 16:22
Is this also the case when using v3.0 (which is now set on the provider)?

**Comment by martinbean** [comment] 2019-03-29 16:23
@driesvints That’s calling **https://graph.facebook.com/v3.0/oauth/access_token**, yeah.

**Comment by driesvints** [comment] 2019-03-29 16:26
Urgh. Well, I'm open to suggestions. I guess an extra call really is the only way? Or do we need to refactor the way this works in general?

**Comment by martinbean** [comment] 2019-03-29 16:31
@driesvints I think it’s just Facebook being Facebook to be honest 😄

Yeah, the only way I can see to get the expiration time for a Facebook access token is making this second, debug token request.

I opened this Issue to basically just feel out how open you were to having Socialite make a second HTTP request to get the expiration time. If you’re happy with this, then I’m happy to put together the PR for it.

**Comment by driesvints** [comment] 2019-03-29 16:48
I guess if it's the only way we don't really have another choice? 😄

**Comment by martinbean** [comment] 2019-03-30 15:49
@driesvints No problem. Should I go ahead a create a PR for that, then?

**Comment by driesvints** [comment] 2019-03-30 15:57
@martinbean yeah feel free!

**Comment by martinbean** [comment] 2019-03-30 16:00
@driesvints Cool. I’ll get that done in the next couple of days then 👍

**Comment by derekmd** [comment] 2020-05-30 00:37
I created branch https://github.com/laravel/socialite/compare/4.0...derekmd:fix-missing-facebook-token-expiry but I don't have a Facebook account to test it live.

If anyone wants this fixed and has 5 minutes to spare, perform these steps on your Socialite-integrated app's local environment:

1. Configure my Socialite changes by editing composer.json with:

   ```
   "repositories": [
       {
           "type": "vcs",
           "url": "https://github.com/derekmd/socialite"
       }
   ],
   "require": {
       "laravel/socialite": "dev-fix-missing-facebook-token-expiry as 4.3.2",
   }
   ```
2. `composer update laravel/socialite` to download the code
3. Add `dump(Socialite::driver('facebook')->user())` to your application's Facebook callback endpoint
4. Confirm the user field `'expires_at'` is filled in with a Unix timestamp integer.
5. Revert step 1 & 3 changes and run `composer update laravel/socialite` again.

Once it's confirmed the APIs behave as documented, I can submit the 4.x pull request.

**Comment by driesvints** [comment] 2020-06-02 09:31
Don't have a Facebook account either so any help is appreciated.

**Comment by driesvints** [comment] 2020-06-19 14:05
Gonna close this after confirming the current implementation works.

**Closed by driesvints** 2020-06-19 14:05 UTC
Labels: bug, help wanted
