### ISSUE TITLE
Retrieving the nickname by calling $user->getNickname() does not work

### ISSUE THREAD

**Issue by connecteev** [laravel/socialite#384] opened 2019-08-08 01:43 UTC
- Socialite Version: #.#.# "laravel/socialite": "^4.0",
- Laravel Version: #.#.# 5.8
- PHP Version: #.#.# 7.2
- Database Driver & Version: MySQL 8.0

### Description:
Attempting to retrieve the nickname (username) in the oAuth callback does not work.

According to the documentation:
https://laravel.com/docs/5.8/socialite#retrieving-user-details
All of these work fine if invoked in the callback:
```
$user->getId();
$user->getName();
$user->getEmail();
$user->getAvatar();
```
except ```$user->getNickname();```

I tried this with Google and Linkedin, and they both did not work. Twitter and Facebook have not been tested. Github was the only one that worked fine.

### Steps To Reproduce:
The usual steps as described here https://laravel.com/docs/5.8/socialite#installation

Sample code:

```

<?php

namespace App\Http\Controllers\api\Auth;

use App\Models\User;
use App\Models\UserSocial;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\Controller;
use Laravel\Socialite\Two\InvalidStateException;
use Tymon\JWTAuth\JWTAuth;

class SocialLoginController extends Controller
{
    protected $auth;

    public function __construct(JWTAuth $auth)
    {
        $this->auth = $auth;
        $this->middleware(['social']);
    }

    public function redirect($service)
    {
        return Socialite::driver($service)->stateless()->redirect();
    }

    public function callback($service)
    {
        try {
            $serviceUser = Socialite::driver($service)->stateless()->user();
        } catch (\Exception $e) {
            return redirect(env('CLIENT_BASE_URL') . '/auth/social-callback?error=Unable to login using ' . $service . '. Please try again' . '&origin=login');
        }

        $email = $serviceUser->getEmail();
        var_dump($serviceUser->getEmail());
        var_dump($serviceUser->getAvatar());
        var_dump($serviceUser->getName());
        var_dump($serviceUser->getNickname()); // COMES BACK EMPTY
        var_dump($serviceUser->getId());
        exit;
        $user = $this->getExistingUser($serviceUser, $email, $service);
        $newUser = false;
        if (!$user) {
            $newUser = true;
            $user = User::create([
                'name' => $serviceUser->getName(),
                'email' => $email,
                'password' => ''
            ]);
        }

        if ($this->needsToCreateSocial($user, $service)) {
            UserSocial::create([
                'user_id' => $user->id,
                'social_id' => $serviceUser->getId(),
                'service' => $service
            ]);
        }

        return redirect(env('CLIENT_BASE_URL') . '/auth/social-callback?token=' . $this->auth->fromUser($user) . '&origin=' . ($newUser ? 'register' : 'login'));
    }

    public function needsToCreateSocial(User $user, $service)
    {
        return !$user->hasSocialLinked($service);
    }

    public function getExistingUser($serviceUser, $email, $service)
    {
        return User::where('email', $email)->orWhereHas('social', function ($q) use ($serviceUser, $service) {
            $q->where('social_id', $serviceUser->getId())->where('service', $service);
        })->first();
    }
}

```

**Comment by driesvints** [comment] 2019-08-08 13:28
I don't think there is a nickname anymore for Google since they deprecated their Google+ api. 

Linkedin also doesn't provides a nickname with their `r_liteprofile` scope. For the new Linkedin API we had to downgrade the `r_basicprofile` scope to the `r_liteprofile` scope. See the reasoning here: https://github.com/laravel/socialite/issues/309

It seems this is a sort of duplicate of https://github.com/laravel/socialite/issues/368 so let's continue the discussion there.

**Closed by driesvints** 2019-08-08 13:28 UTC

**Comment by connecteev** [comment] 2019-08-08 15:16
Thanks @driesvints for the clarification. Yes, I've seen #368 but since that's focused on just Linkedin, thought this was unique...but I guess not!

As an aside, do you know of a repo with a working example of socialite that makes use of detailed scopes (r_basicprofile and above instead of r_liteprofile) for Google, Linkedin, Twitter and Facebook? Trying to retrieve more than just the basic info, and it will be different for all 4 of these providers. Any pointers?

**Comment by driesvints** [comment] 2019-08-08 16:09
@connecteev normally the scopes feature of Socialite allows for this but as the linked issue says this doesn't works atm for the LinkedIn provider: https://laravel.com/docs/5.8/socialite#access-scopes

**Comment by connecteev** [comment] 2019-08-08 17:17
@driesvints thanks, I'll give scopes another go....was just hoping for someplace where it had been done (nicely) before...you know, lazy programming?! :)

**Comment by Anticom** [comment] 2020-06-15 14:59
Why did this issue get closed? I've got the same issue with the Facebook Provider.

The DocBlock of Socialite's [AbstractUser](https://github.com/laravel/socialite/blob/4.0/src/AbstractUser.php#L65) clearly states that the `getNickname()` does not return null. Looking at the sources of the [FacebookProvider](https://github.com/laravel/socialite/blame/4.0/src/Two/FacebookProvider.php#L112) `nickname` has been set to null for two years. Can't we use at least the first name etc. to give the nickname at least some value?

**Comment by Fenslau** [comment] 2024-12-30 03:28
\SocialiteProviders\Mailru\Provider 
Undefined array key "nickname"
Please. add null safe operators!!!!
